apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/label: "rlcraft-deploy"
  name: "kaniko-kubectl-pod"
spec:
  serviceAccountName: jenkins
  restartPolicy: Never
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - sh
    - -c
    - sleep infinity
    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker
    - name: workspace-volume
      mountPath: /workspace
    - name: workspace-volume
      mountPath: /home/jenkins/agent
  - name: kubectl
    image: bitnami/kubectl:latest
    command:
    - sh
    - -c
    - sleep infinity
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/agent
  volumes:
  - name: docker-config
    secret:
      secretName: dockerhub-credentials
  - name: workspace-volume
    emptyDir: {}
  nodeSelector:
    kubernetes.io/os: linux

