apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: jenkins
spec:
  restartPolicy: Never
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    command:
      - /kaniko/executor
    args:
      - "--dockerfile=Dockerfile"
      - "--context=dir:///workspace"
      - "--destination=docker.io/headroaster/rlcraft-server:latest"
      - "--verbosity=info"
    workingDir: /workspace  
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker/
      - name: workspace-volume
        mountPath: /workspace
  volumes:
    - name: kaniko-secret
      secret:
        secretName: dockerhub-credentials
    - name: workspace-volume
      emptyDir: {}

