apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: jenkins
spec:
  restartPolicy: Never
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /busybox/sh
      args:
        - "-c"
        - "sleep 3600"
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker/
        - name: workspace-volume
          mountPath: /workspace
  volumes:
    - name: kaniko-secret
      secret:
        secretName: dockerhub-credentials
    - name: workspace-volume
      emptyDir: {}

